title: "Frank Dam Lab"
email: frank.dam@university.edu
description: >-
  Research laboratory focused on Dynamic & Adaptive Memory
baseurl: ""
url: "https://frank-dam-lab.github.io"

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/