title: "Dynamic & Adaptive Memory Lab"
email: frank.dam@university.ac.uk
description: >-
  PI: Dr Darya Frank
baseurl: "https://frankmemorylab.github.io"
url: ""

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
