menu:
- {name: 'team', url: '/people'}
- {name: 'news & updates', url: '/news'}
- {name: 'publications', url: '/publications'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Darya Frank', title: 'Principal Investigator', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/DF4.png'}
- {name: 'Marta Garcia Huescar', title: 'PhD Student', email: 'marta.garcia@ctb.upm.es', institution: 'Universidad Politecnica de Madrid', image: 'assets/img/MGH.jpg', text: 'Researches the functional correlates of superageing (co-supervised with Bryan Strange).'}
- {name: 'Haoran Guan', title: 'PhD Student', email: 'haoran.guan@manchester.ac.uk', image: 'assets/img/graduate-student.jpg', text: 'Researches brain lateralisation and its affect on cognition across life span (co-supervised with Daniela Montaldi).'}
- {name: 'Aysha Janjua', title: 'MRes Student'}
- {name: 'Zhiyun Qin', title: 'MRes Student'}

social:
- {icon: 'github', link: 'https://github.com/frank-dam-lab'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/darya-frank.bsky.social'}

contacts:
- {name: 'Darya Frank', title: 'Royal Society URF', department: 'Andrew Mayes Centre for Cognitive Neuroscience', institution: 'The University of Manchester', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/contact.jpg'}
