menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Darya Frank', title: 'Royal Society URF', department: 'Andrew Mayes Centre for Cognitive Neuroscience', institution: 'The University of Manchester', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/frank-dam-lab'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/darya-frank.bsky.social'}

contacts:
- {name: 'Darya Frank', title: 'Royal Society URF', department: 'Andrew Mayes Centre for Cognitive Neuroscience', institution: 'The University of Manchester', email: 'darya.frank@manchester.ac.uk', image: 'assets/img/contact.jpg'}
